### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [Hack-a-Day/Vectorscope#11]
Hello!

I found your project from https://hackaday.com/2023/12/12/can-googles-new-ai-read-your-datasheets-for-you/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code, documentation and design files in any purpose?
It would be great to see any popular open source license.

**Comment by hexagon5un** [comment]
Makes sense, and was absolutely our intention.

Added MIT LICENSE.txt.
